name: generate-snake

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: Platane/snk@v3
        with:
          github_user_name: KuaaMU
          outputs: |
            dist/github-contribution-grid-snake-dark.svg?color_snake=green&color_dots=#161b22,#58a6ff,#1f6feb,#388bfd,#1158c7
            dist/github-contribution-grid-snake-dark.gif

      - name: Deploy to output branch
        run: |
          cd dist
          git init
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add -A
          git commit -m "update snake"
          git push --force https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git main:output
